config/routes.rb
Rails.application.routes.draw do
 
  resources :line_items
  resources :carts
  get 'gallery/index'
  devise_for :users
  get 'dashboard/index'
  resources :stores
  get 'admin/login'
  get 'home/index'
  post 'admin/login'
  get 'admin/logout'
  get 'gallery/index'
  get 'gallery/search'
  post 'gallery/search'
  get 'gallery/checkout'
  get 'gallery/purchase_complete'
  post 'gallery/checkout'
  resources :stores
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
    has_one_attached :store_image
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
    before_action :set_store, only: [:show, :edit, :update, :destroy]
    before_action :admin_logged_in?

    def index
      #@products = Product.all
      @stores    = Store.all 
    end
  
    def show
    end
  
    def new
      #@product = Product.new
       @store   = Store.new
    end
  
    def edit
    end
  
    def create
      @store = Store.new(store_params)

        respond_to do |format|
        if @store.save
          format.html { redirect_to @store, notice: "Store was successfully created." }
          format.json { render :show, status: :created, location: @store }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @store.errors, status: :unprocessable_entity }
        end
        end  
    end
  
    def update
      respond_to do |format|
        if @store.update(store_params)
          format.html { redirect_to @store, notice: "Store was successfully updated." }
          format.json { render :show, status: :ok, location: @store }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @store.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def destroy
      @store.destroy
      respond_to do |format|
        format.html { redirect_to stores_url, notice: "Store was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    def admin_logged_in?
      if session[:admin].nil?
        flash[:notice] = "You should login as an admin to continue"
         redirect_to admin_login_path
      end
    end
  

  private

    def set_store
      @store = Store.find(params[:id])
    end

    def store_params
      params.require(:store).permit(:name, :description, :color, :price, :theme, :material, :design, :netWeight, :store_image)
    end

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
  <div class="form-group col-md-4">
    <%= form.label :name %>
    <%= form.text_field :name,class: "form-control" %>
  </div>
  </div>

  <div class="row">
  <div class="form-group col-md-4">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>
  </div>

  <div class="row">
  <div class="form-group col-md-4">
    <%= form.label :color %>
    <%= form.text_field :color, class: "form-control" %>
  </div>
  </div>

  <div class="row">
  <div class="form-group col-md-4">
  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price,class: "form-control" %>
  </div>
  </div>

  <div class="row">
  <div class="form-group col-md-4">
    <%= form.label :theme %>
    <%= form.text_field :theme,class: "form-control" %>
  </div>
  </div>

  <div class="row">
  <div class="form-group col-md-4">
    <%= form.label :material %>
    <%= form.text_field :material, class: "form-control" %>
  </div>
  </div>

  <div class="row">
  <div class="form-group col-md-4">
    <%= form.label :design %>
    <%= form.text_field :design, class: "form-control" %>
  </div>  
  </div>

  <div class="row">
  <div class="form-group col-md-4">
    <%= form.label :netWeight %>
    <%= form.text_field :netWeight, class: "form-control" %>
  </div>
  </div>

  <div class="row">
  <div class="form-group col-md-4"> 
  <%= form.label :store_image %>
  <%= form.file_field :store_image, class: "form-control" %>
  </div>
  </div>

  <div class="actions">
      <%= form.submit 'Create', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store, class: "btn btn-warning"%> |
<%= link_to 'Back', stores_path, class: "btn btn-default" %>

app/views/stores/index.html.erb
<%= flash_messages %>

<h1>Stores</h1>

<div class="product-block">
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th class="col-md-2">Name</th>
      <th class="col-md-4">Description</th>
      <th class="col-md-4">Color</th>
      <th class="col-md-4">Price</th>
      <th class="col-md-4">Theme</th>
      <th class="col-md-4">Material</th>
      <th class="col-md-4">Design</th>
      <th class="col-md-4">Netweight</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td  class="col-md-2"><%= store.name %></td>
        <td  class="col-md-2"><%= store.description %></td>
        <td  class="col-md-2"><%= store.color %></td>
        <td  class="col-md-2"><%= store.price %></td>
        <td  class="col-md-2"><%= store.theme %></td>
        <td  class="col-md-2"><%= store.material %></td>
        <td  class="col-md-2"><%= store.design %></td>
        <td  class="col-md-2"><%= store.netWeight %></td>
        <td><div class="picture">
           <%= image_tag(store.store_image) if store.store_image.attached? %>
        </div>
        </td>
        <td  class="col-md-4">
             <%= link_to 'Show', store , class: "btn btn-info"%>
             <%= link_to 'Edit', edit_store_path(store), class: "btn  btn-warning" %>
             <%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Store', new_store_path, class: "btn btn-primary" %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path, class: "btn btn-default" %>

app/views/stores/show.html.erb
<%= flash_messages %>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @store.description %>
</p>

<p>
  <strong>Color:</strong>
  <%= @store.color %>
</p>

<p>
  <strong>Price:</strong>
  <%= @store.price %>
</p>

<p>
  <strong>Theme:</strong>
  <%= @store.theme %>
</p>

<p>
  <strong>Material:</strong>
  <%= @store.material %>
</p>

<p>
  <strong>Design:</strong>
  <%= @store.design %>
</p>

<p>
  <strong>Netweight:</strong>
  <%= @store.netWeight %>
</p>

<%= link_to 'Edit', edit_store_path(@store), class: "btn btn-warning" %> |
<%= link_to 'Back', stores_path, class: "btn btn-default" %>